name: test workflow

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-test-job
        id: my-test-job
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Josh Kirwin
      - name: log-time
        run: echo ${{ steps.my-test-job.outputs.time }}
