name: Sample workflow

on: push

jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
  my-second-test-job:
    runs-on: ubuntu-latest
    needs: [my-test-job]
    steps:
      - name: "echo another string"
        run: echo 'Hello world yet again!'
